-- Velora Phase 1 baseline (PostgreSQL). Generated from server/db/schema.ts.
-- Apply with drizzle-kit or psql. Runtime dev store needs no DB.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, name TEXT);
CREATE TABLE IF NOT EXISTS organizations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS organization_members (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, user_id UUID NOT NULL, role TEXT NOT NULL DEFAULT 'owner');
CREATE TABLE IF NOT EXISTS workspaces (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, name TEXT NOT NULL DEFAULT 'Default');
CREATE TABLE IF NOT EXISTS websites (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, url TEXT NOT NULL, cms TEXT, website_type TEXT, primary_domain TEXT, target_countries JSONB DEFAULT '[]', languages JSONB DEFAULT '[]', analysis JSONB);
CREATE TABLE IF NOT EXISTS brands (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, website_id UUID, data JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, data JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS audiences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, data JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS audience_segments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, audience_id UUID, data JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS goals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, data JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS competitors (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, domain TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'business', data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS keywords (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, keyword TEXT NOT NULL, cluster_id UUID, intent TEXT, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS keyword_clusters (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, name TEXT NOT NULL, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS seo_audits (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, website_id UUID, status TEXT NOT NULL DEFAULT 'pending', summary JSONB, is_mock BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS seo_issues (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, audit_id UUID, severity TEXT NOT NULL DEFAULT 'info', title TEXT NOT NULL, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS content_campaigns (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, name TEXT NOT NULL, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS content_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, website_id UUID, campaign_id UUID, channel TEXT, status TEXT NOT NULL DEFAULT 'idea', approval_state TEXT NOT NULL DEFAULT 'none', publication_state TEXT NOT NULL DEFAULT 'unpublished', data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS social_accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, provider TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'not_connected', handle TEXT, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS social_posts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, provider TEXT, status TEXT NOT NULL DEFAULT 'draft', data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS social_metrics (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, provider TEXT NOT NULL, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS integrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, provider TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'not_connected', credentials_ref TEXT, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS analytics_sources (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, provider TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'not_connected', data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS analytics_snapshots (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, source TEXT NOT NULL, data JSONB DEFAULT '{}', is_mock BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS backlinks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, domain TEXT NOT NULL, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS reviews (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, source TEXT NOT NULL, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS automations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, name TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT FALSE, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS automation_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, automation_id UUID, status TEXT NOT NULL DEFAULT 'queued', data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS reports (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, name TEXT NOT NULL, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID, type TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', progress INTEGER NOT NULL DEFAULT 0, retry_count INTEGER NOT NULL DEFAULT 0, error TEXT, payload JSONB DEFAULT '{}', result JSONB, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS onboarding_progress (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID NOT NULL, current_step INTEGER NOT NULL DEFAULT 1, completed_steps JSONB DEFAULT '[]', steps JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS audit_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), organization_id UUID, user_id UUID, action TEXT NOT NULL, data JSONB DEFAULT '{}');
